# supported: [en, zh_TW, es, fr, de, uk, pt_BR, it, he, hu, nl_NL, pl, ja, ca, sv, ru, da, tr, he, el, ko]
supported: [en, zh_TW, es, fr, de, uk, pt_BR, it, he, hu, nl_NL, pl, ja, ca]
fallbacks:
  zh: zh_TW
  pt: pt_BR
  nl: nl_NL
