# question_poll:
#   poll_type: poll
#   process_name: Question round
#   process_subtitle: Ask an open ended question, with a deadline
#   default_duration_in_days: 3

count:
  poll_type: count
  process_name_i18n: decision_tools_card.count_title
  process_subtitle_i18n: poll_count_form.tool_tip_collapsed
  default_duration_in_days: 3
  poll_options:
    - key: accept
      name_i18n: poll_count_options.accept
      icon: agree
      meaning_i18n: poll_count_vote_form.accept_meaning
      prompt_i18n: poll_count_vote_form.accept_prompt
      color: '#70C9F8'
    - key: decline
      name_i18n: poll_count_options.decline
      icon: disagree
      meaning_i18n: poll_count_vote_form.decline_meaning
      prompt_i18n: poll_count_vote_form.decline_prompt
      color: "#C8E56E"

check:
  poll_type: proposal
  process_name_i18n: decision_tools_card.check_title
  process_subtitle_i18n: poll_check_options.check_subtitle
  process_subtitle: Invite people to ask questions, comment and respond within a set timeframe
  process_url: https://help.loomio.com/en/user_manual/polls/proposal_types/index.html#sense-check
  default_duration_in_days: 3
  tags_i18n:
    - decision_tools_card.check_title
  poll_options:
    - key: looks_good
      name_i18n: poll_check_options.looks_good
      icon: agree
      meaning_i18n: poll_check_options.looks_good_meaning
      prompt_i18n: poll_check_options.looks_good_prompt
      color: '#70C9F8'
    - key: question
      name_i18n: poll_check_options.question
      icon: abstain
      meaning_i18n: poll_check_options.question_meaning
      prompt_i18n: poll_check_options.question_prompt
      color: '#70C9F8'
    - key: concerned
      name_i18n: poll_check_options.concerned
      icon: disagree
      meaning_i18n: poll_check_options.concerned_meaning
      prompt_i18n: poll_check_options.concerned_prompt
      color: "#C8E56E"

# proposal:
#   poll_type: proposal
#   process_name_i18n: decision_tools_card.proposal_title
#   process_subtitle_i18n: poll_proposal_form.tool_tip_collapsed
#   process_url: https://help.loomio.com/en/user_manual/getting_started/decisions#loomio-proposal
#   default_duration_in_days: 7
#   poll_options:
#     - key: agree
#       name_i18n: poll_proposal_options.agree
#       icon: agree
#       meaning_i18n: poll_proposal_options.agree_meaning
#       prompt_i18n: poll_proposal_vote_form.agree_reason_placeholder
#       color: '#70C9F8'
#     - key: abstain
#       name_i18n: poll_proposal_options.abstain
#       icon: abstain
#       meaning_i18n: poll_proposal_options.abstain_meaning
#       prompt_i18n: poll_proposal_options.abstain_prompt
#       color: "#C8E56E"
#     - key: disagree
#       name_i18n: poll_proposal_options.disagree
#       icon: disagree
#       meaning_i18n: poll_proposal_options.disagree_meaning
#       prompt_i18n: poll_proposal_vote_form.disagree_reason_placeholder
#       color: "#D38FE1"

meeting:
  poll_type: meeting
  meeting_duration: 60
  process_name_i18n: decision_tools_card.meeting_title
  process_subtitle_i18n: poll_meeting_form.tool_tip_collapsed
  process_url: https://help.loomio.com/en/user_manual/polls/proposal_types#time-poll
  chart_type: grid
  min_score: 0
  max_score: 2
  default_duration_in_days: 3
  can_respond_maybe: true

poll:
  poll_type: poll
  process_name_i18n: poll_common_form.voting_methods.simple_poll
  process_subtitle_i18n: poll_poll_form.tool_tip_collapsed
  process_url: https://help.loomio.com/en/user_manual/polls/proposal_types#simple-poll
  default_duration_in_days: 3

dot_vote:
  poll_type: dot_vote
  process_name_i18n: decision_tools_card.dot_vote_title
  process_subtitle_i18n: poll_dot_vote_form.tool_tip_collapsed
  process_url: https://help.loomio.com/en/user_manual/polls/proposal_types#dot-vote
  default_duration_in_days: 3

score:
  poll_type: score
  process_name_i18n: decision_tools_card.score_title
  process_subtitle_i18n: poll_score_form.tool_tip_collapsed
  process_url: https://help.loomio.com/en/user_manual/polls/proposal_types#score-poll
  default_duration_in_days: 3

ranked_choice:
  poll_type: ranked_choice
  process_name_i18n: decision_tools_card.ranked_choice_title
  process_subtitle_i18n: poll_ranked_choice_form.tool_tip_collapsed
  process_url: https://help.loomio.com/en/user_manual/polls/proposal_types#ranked-choice

advice:
  poll_type: proposal
  process_name_i18n: decision_tools_card.advice_title
  process_subtitle_i18n: poll_proposal_form.advice_subtitle
  tags_i18n:
    - poll_common.advice_process
  poll_options:
    - key: looks_good
      name_i18n: poll_check_options.looks_good
      icon: agree
      meaning_i18n: poll_check_options.looks_good_meaning
      prompt_i18n: poll_check_options.looks_good_prompt
      color: '#70C9F8'
      default: true
    - key: not_sure
      name_i18n: poll_check_options.not_sure
      icon: abstain
      meaning_i18n: poll_check_options.not_sure_meaning
      prompt_i18n: poll_check_options.not_sure_prompt
      color: '#70C9F8'
      default: true
    - key: concerned
      name_i18n: poll_check_options.concerned
      icon: disagree
      meaning_i18n: poll_check_options.concerned_meaning
      prompt_i18n: poll_check_options.concerned_prompt
      color: "#C8E56E"
      default: true

check:
  poll_type: proposal
  process_name_i18n: decision_tools_card.check_title
  process_subtitle_i18n: poll_check_options.check_subtitle
  tags_i18n:
    - decision_tools_card.check_title
  poll_options:
    - key: looks_good
      name_i18n: poll_check_options.looks_good
      icon: agree
      meaning_i18n: poll_check_options.looks_good_meaning
      prompt_i18n: poll_check_options.looks_good_prompt
      color: '#70C9F8'
      default: true
    - key: not_sure
      name_i18n: poll_check_options.not_sure
      icon: abstain
      meaning_i18n: poll_check_options.not_sure_meaning
      prompt_i18n: poll_check_options.not_sure_prompt
      color: '#70C9F8'
      default: true
    - key: concerned
      name_i18n: poll_check_options.concerned
      icon: disagree
      meaning_i18n: poll_check_options.concerned_meaning
      prompt_i18n: poll_check_options.concerned_prompt
      color: "#C8E56E"
      default: true

consent:
  poll_type: proposal
  process_name: Consent
  process_subtitle: Ensure nobody objects to your proposal
  default_duration_in_days: 7
  tags_i18n:
    - poll_common.consent_process
  poll_options:
    - name: Consent
      icon: agree
      meaning: The proposal is safe to try
      prompt: Do you have any other thoughts about the proposal?
    - name: Object
      icon: agree
      meaning: There is a serious problem with this proposal
      prompt: How would you change the proposal to address the problem?

consensus:
  poll_type: proposal
  process_name: Consensus
  process_subtitle: Improve a proposal so that everyone is supportive of it
  default_duration_in_days: 7
  tags_i18n:
    - poll_common.consensus_process
  poll_options:
    - key: agree
      name_i18n: poll_proposal_options.agree
      icon: agree
      meaning_i18n: poll_proposal_options.agree_meaning
      prompt_i18n: poll_proposal_vote_form.agree_reason_placeholder
      color: '#70C9F8'
      default: true
    - key: abstain
      name_i18n: poll_proposal_options.abstain
      icon: abstain
      meaning_i18n: poll_proposal_options.abstain_meaning
      prompt_i18n: poll_proposal_options.abstain_prompt
      color: "#C8E56E"
      default: true
    - key: disagree
      name_i18n: poll_proposal_options.disagree
      icon: disagree
      meaning_i18n: poll_proposal_options.disagree_meaning
      prompt_i18n: poll_proposal_vote_form.disagree_reason_placeholder
      color: "#D38FE1"
      default: true
    - key: block
      name_i18n: poll_proposal_options.block
      icon: block
      meaning_i18n: poll_proposal_options.block_meaning
      prompt_i18n: poll_proposal_vote_form.block_reason_placeholder
      color: "#999FDE"

gradients_of_agreement:
  poll_type: proposal
  process_name_i18n: gradients_of_agreement.process_name
  process_subtitle_i18n:  gradients_of_agreement.process_subtitle
  # process_intro: gradients_of_agreement.process_intro
  default_duration_in_days: 5
  tags_i18n:
    - gradients_of_agreement.process_name
  poll_options:
    - key: endorsement
      name_i18n: gradients_of_agreement.whole_hearted_endorsement
      icon: agree
      meaning_i18n: gradients_of_agreement.whole_hearted_endorsement_meaning
      color: '#70C9F8'
    - key: agreement_with_contention
      name_i18n: gradients_of_agreement.agreement_with_contention
      icon: agree
      meaning_i18n: gradients_of_agreement.agreement_with_contention_meaning
      color: '#70C9F8'
    - key: support_with_reservations
      name_i18n: gradients_of_agreement.support_with_reservations
      icon: agree
      meaning_i18n: gradients_of_agreement.support_with_reservations_meaning
      color: '#70C9F8'
    - key: abstain
      name_i18n: poll_proposal_options.abstain
      icon: abstain
      meaning_i18n: gradients_of_agreement.abstain_meaning
      prompt_i18n: poll_proposal_options.abstain_prompt
      color: "#C8E56E"
    - key: more_discussion_needed
      name_i18n: gradients_of_agreement.more_discussion_needed
      icon: disagree
      meaning_i18n: gradients_of_agreement.more_discussion_needed_meaning
      prompt_i18n: gradients_of_agreement.disagree_reason_placeholder
      color: "#D38FE1"
    - key: dont_like_but_will_support
      name_i18n: gradients_of_agreement.dont_like_but_will_support
      icon: disagree
      meaning_i18n: gradients_of_agreement.dont_like_but_will_support_meaning
      prompt_i18n: gradients_of_agreement.disagree_reason_placeholder
      color: "#D38FE1"
    - key: serious_disagreement
      name_i18n: gradients_of_agreement.serious_disagreement
      icon: disagree
      meaning_i18n: gradients_of_agreement.serious_disagreement_meaning
      prompt_i18n: gradients_of_agreement.disagree_reason_placeholder
      color: "#D38FE1"
    - key: veto
      name_i18n: gradients_of_agreement.veto
      icon: block
      meaning_i18n: gradients_of_agreement.veto_meaning
      prompt_i18n: gradients_of_agreement.block_reason_placeholder
      color: "#999FDE"
